apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: ci
on:
  push:
    branches: ['**']

jobs:
  test:
    services:
      db:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nomads_test

    steps:
      - name: Checkout
        uses: https://github.com/cloudbees-io/checkout@v1
      - name: Run tests in Ubuntu
        uses: docker://ubuntu:24.04
        shell: bash
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/nomads_test
        run: |
          # update package manager
          apt-get update

          # install C compiler
          apt-get install -y build-essential

          # install Git
          apt-get install -y git

          # install Curl for Ruby gem downloads
          apt-get install -y curl

          # install packages for node modules
          apt-get install -y fontforge ttfautohint

          # install ruby
          apt-get install -y zlib1g-dev libssl-dev libreadline-dev libpq-dev libffi-dev
          RUBY_VERSION=$(cat .ruby-version 2>/dev/null || echo "3.2.2")
          echo "Ruby Version: $RUBY_VERSION"
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          eval "$(~/.rbenv/bin/rbenv init - bash)"
          git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
          if ! rbenv install $RUBY_VERSION ; then cat /tmp/ruby-build.*.log && exit 1; fi
          rbenv global $RUBY_VERSION
          gem install bundler:2.3.26

          # setup app
          bundle install
          export RAILS_ENV=test

          # build assets
          cp grunt-aws.dev.json grunt-aws.json
          nvm install lts/hydrogen
          nvm use lts/hydrogen
          npm i -g yarn
          rm -rf ./node_modules
          yarn install

          # setup database
          bundle exec rake db:schema:load
          bin/rails db:environment:set RAILS_ENV=test
          bin/rails db:migrate RAILS_ENV=test

          # run tests
          bundle exec rspec --exclude-pattern "**/feature/*_spec.rb"
